App/urls.py
from django.urls import path

from . import views

app_name = 'App'
urlpatterns = [
	path('', views.index, name='index'),
	path('tareas/gestion', views.tareas_gestion, name='tareas_gestion'),
	path('tareas/nueva', views.tareas_nueva, name='tareas_nueva'),
	path('tareas/actualizar/<int:pk>', views.tareas_actualizar, name='tareas_actualizar'),
	path('tareas/borrar/<int:pk>', views.tareas_borrar, name='tareas_borrar'),
	path('tareas/consultar', views.tareas_consultar, name='tareas_consultar'),
]

Fullstack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('App/', include('App.urls')),
]

App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tarea(models.Model):
	tarea_fecha_de_creacion = models.DateTimeField('fecha creacion')
	tarea_descripcion = models.TextField('descripcion')
	tarea_estado = models.BooleanField('finalizada')
	tarea_fecha_de_vencimiento = models.DateTimeField('fecha vencimiento')
	tarea_autor = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.tarea_descripcion

App/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate
from django.utils import timezone

from .models import Tarea

# Create your views here.
def index(request):
	return render(request, 'App/inicio.html')

def tareas_gestion(request):
	tareas_lista = Tarea.objects.order_by('pk')
	context = {'tareas_lista': tareas_lista}
	return render(request, 'App/tarea_gestion.html', context)

def tareas_nueva(request):
	if request.method == 'POST':
		tarea = Tarea()
		tarea.tarea_fecha_de_creacion = timezone.now()
		tarea.tarea_descripcion = request.POST['descripcion']
		tarea.tarea_estado = False
		tarea.tarea_fecha_de_vencimiento = timezone.now()#request.POST['fecha_de_vencimiento']
		tarea.tarea_autor = request.user
		tarea.save()
		return redirect('/App/tareas/gestion')
	else:
		tarea=Tarea()
	context = {'tarea': tarea}
	return render(request, 'App/tarea_nueva.html', context)

def tareas_actualizar(request, pk):
	if request.method == 'POST':
		tarea = get_object_or_404(Tarea, pk=pk)
		tarea.tarea_fecha_de_creacion = timezone.now()
		tarea.tarea_descripcion = request.POST['descripcion']
		tarea.tarea_estado = request.POST['estado']
		tarea.tarea_fecha_de_vencimiento = timezone.now()#request.POST['fecha_de_vencimiento']
		tarea.tarea_autor = request.user
		tarea.save()
		return redirect('/App/tareas/gestion')
	else:
		tarea = get_object_or_404(Tarea, pk=pk)
	context = {'tarea': tarea}
	return render(request, 'App/tarea_actualizar.html', context)

def tareas_borrar(request, pk):
	if request.method == 'POST':
		tarea = Tarea.objects.get(pk=pk)
		tarea.delete()
		return redirect('/App/tareas/gestion')
	else:
		tarea = get_object_or_404(Tarea, pk=pk)
		context = {'tarea': tarea}
	return render(request, 'App/tarea_borrar.html', context)

def tareas_consultar(request):
	tareas_lista = Tarea.Objects.order_by('fecha_creacion')#Agregar los diferentes parametros de busqueda
	context = {'tareas_lista': tareas_lista}
	return render(request, 'App/tarea_consultar.html', context)

App/templates/App/head.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'App/css/theme.css' %}">
</head>

App/templates/App/inicio.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "App/head.html" %}
<body>
  <div class="py-5 h-100">
    <div class="container">
      <div class="row h-100">
        <div class="col-md-3"> </div>
        <div class="col-md-6 d-inline-flex align-items-center justify-content-center">
          <div class="card text-white p-5 bg-primary text-center">
            <div class="card-body">
              <h1 class="mb-4">Gestión de Tareas</h1>
              <a class="btn btn-secondary" href="https://drsgps.co/identity" >Iniciar Sesión</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

App/templates/App/tarea_actualizar.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "App/head.html" %}
<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body bg-primary">
              <h2>Actualizar Tarea</h2>
              <form class="" method="POST">
                {% csrf_token %}
                <div class="form-group"><label for="exampleInputEmail1">Descripción:</label><textarea class="form-control form-control-sm" id="exampleTextarea" rows="3" name="descripcion">{{tarea.tarea_descripcion}}</textarea></div>
                <div class="form-group"> <label>Fecha de Vencimiento:</label>
                  <input type="date" class="form-control" value="{{tarea.tarea_fecha_de_vencimiento}}"name="fecha_de_vencimiento"></div>
                <div class="form-group">
                  <div class="form-check form-control-lg form-check-inline">
                    <input class="form-check-input" type="radio" name="estado" id="exampleRadios1" value="True" checked=""><label class="form-check-label" for="exampleRadios1">Pendiente</label></div>
                  <div class="form-check form-check-inline form-control-lg">
                    <input class="form-check-input" type="radio" name="estado" id="exampleRadios1" value="False" checked=""><label class="form-check-label" for="exampleRadios1">Finalizada</label></div>
                </div>
                <button type="submit" class="btn btn-secondary">Guardar</button>
              </form>
              <a class="btn btn-secondary" href="/App/tareas/gestion">Cancelar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

App/templates/App/tarea_borrar.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "App/head.html" %}
<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body bg-warning">
              <h2>Borrar Tarea</h2>
              <form class="" method="POST">
                {% csrf_token %}
                <div class="form-group"><label for="exampleInputEmail1">Descripción:</label><textarea class="form-control form-control-sm" id="exampleTextarea" rows="3">{{tarea.tarea_descripcion}}</textarea></div>
                <div class="form-group"> <label>Fecha de Vencimiento:</label>
                  <input type="date" class="form-control" value="{{tarea.tarea_fecha_de_vencimiento}}"> </div>
                <div class="form-group">
                  <div class="form-check form-control-lg form-check-inline">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked=""><label class="form-check-label" for="exampleRadios1">Pendiente</label></div>
                  <div class="form-check form-check-inline form-control-lg">
                    <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked=""><label class="form-check-label" for="exampleRadios1">Finalizada</label></div>
                </div>
                <button type="submit" class="btn btn-danger">Borrar</button>
              </form>
              <a class="btn btn-secondary" href="/App/tareas/gestion">Cancelar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

App/templates/App/tarea_gestion.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "App/head.html" %}
<body>
  <div class="py-4">
    <div class="container">
      {% for tarea in tareas_lista %}
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <div class="card text-white bg-primary text-center p-3">
            <div class="card-body">
              <h3 class="mb-4 text-left">{{ tarea.tarea_descripcion }}</h3>
              <p class="text-left">{{ tarea.tarea_fecha_de_vencimiento }}</p>
              <p class="text-left">{{ tarea.tarea_estado }}</p>
            </div>
            <div class="row">
              <div class="col-md-6">
                <a class="btn btn-secondary" href="{% url 'App:tareas_actualizar' tarea.pk %}">Actualizar</a>
              </div>
              <div class="col-md-6">
                <a class="btn btn-secondary" href="{% url 'App:tareas_borrar' tarea.pk %}">Borrar</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-2"></div>
      </div>
      {% endfor %}
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

App/templates/App/tarea_nueva.html
<!DOCTYPE html>
<html>
{% load static %}
{% include "App/head.html" %}
<body>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body bg-primary">
              <h2>Nueva Tarea</h2>
              <form class="" method="POST">
                {% csrf_token %}
                <div class="form-group"><label for="exampleInputEmail1">Descripción:</label><textarea class="form-control form-control-sm" id="exampleTextarea" rows="3" name="descripcion"></textarea></div>
                <div class="form-group"><label>Fecha de Vencimiento:</label>
                  <input type="date" class="form-control" name="fecha_de_vencimiento"> </div>
                <button type="submit" class="btn btn-secondary d-inline-flex">Guardar</button>
              </form>
              <a class="btn btn-secondary" href="/App/tareas/gestion">Cancelar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>